# Generated by Django 5.2.1 on 2025-07-17 10:28

import colorfield.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="نام دسته\u200cبندی"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی مقاله",
                "verbose_name_plural": "دسته\u200cبندی\u200cهای مقاله",
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="brands/")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "برند",
                "verbose_name_plural": "برندها",
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="نام رنگ"
                    ),
                ),
                (
                    "hex_code",
                    colorfield.fields.ColorField(
                        default="#FFFFFF",
                        help_text="مثال: #FFFFFF",
                        image_field=None,
                        max_length=7,
                        samples=[
                            ("#FFFFFF", "white"),
                            ("#000000", "black"),
                            ("#FF0000", "red"),
                            ("#008000", "green"),
                            ("#0000FF", "blue"),
                        ],
                        verbose_name="کد هگز رنگ",
                    ),
                ),
            ],
            options={
                "verbose_name": "رنگ",
                "verbose_name_plural": "رنگ\u200cها",
            },
        ),
        migrations.CreateModel(
            name="SpecificationGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="نام گروه مشخصات"),
                ),
            ],
            options={
                "verbose_name": "گروه مشخصات",
                "verbose_name_plural": "گروه\u200cهای مشخصات",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام تگ")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="شناسه URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "تگ",
                "verbose_name_plural": "تگ\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Warranty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام گارانتی")),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="شرکت ارائه دهنده",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="مدت زمان گارانتی به ماه",
                        verbose_name="مدت گارانتی (ماه)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "terms_conditions",
                    models.TextField(blank=True, verbose_name="شرایط و ضوابط"),
                ),
                (
                    "support_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="شماره تماس پشتیبانی"
                    ),
                ),
                (
                    "registration_required",
                    models.BooleanField(
                        default=False, verbose_name="نیاز به ثبت گارانتی"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "گارانتی",
                "verbose_name_plural": "گارانتی\u200cها",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="categories/"),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="categories/icons/"
                    ),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "brand",
                    models.ManyToManyField(
                        blank=True, related_name="categories", to="store.brand"
                    ),
                ),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="store.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="store.brand",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="products", to="store.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
            },
        ),
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option_price",
                    models.PositiveIntegerField(
                        help_text="قیمت به تومان برای محصول با این ویژگی",
                        verbose_name="قیمت ویژگی",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="تعداد",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "is_active_discount",
                    models.BooleanField(default=False, verbose_name="تخفیف فعال است؟"),
                ),
                (
                    "discount",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="درصد تخفیف",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="درصد تخفیف",
                    ),
                ),
                (
                    "discount_start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ شروع تخفیف"
                    ),
                ),
                (
                    "discount_end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ پایان تخفیف"
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="store.color",
                        verbose_name="رنگ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="store.product",
                        verbose_name="محصول",
                    ),
                ),
                (
                    "warranty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_options",
                        to="store.warranty",
                        verbose_name="گارانتی",
                    ),
                ),
            ],
            options={
                "verbose_name": "ویژگی محصول",
                "verbose_name_plural": "ویژگی\u200cهای محصول",
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="product_gallery/", verbose_name="تصویر"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="متن جایگزین"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="store.productoption",
                        verbose_name="ویژگی محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "گالری تصویر",
                "verbose_name_plural": "گالری تصاویر",
            },
        ),
        migrations.CreateModel(
            name="Specification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام مشخصه")),
                ("data_type", models.CharField(max_length=50, verbose_name="نوع داده")),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="واحد"
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False,
                        help_text="مشخصه اصلی برای محصولات است",
                        verbose_name="مشخصه اصلی",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="spec_definitions",
                        to="store.category",
                        verbose_name="دسته\u200cبندی\u200cها",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="specifications",
                        to="store.specificationgroup",
                        verbose_name="گروه مشخصات",
                    ),
                ),
            ],
            options={
                "verbose_name": "مشخصه",
                "verbose_name_plural": "مشخصات",
            },
        ),
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specification_value",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="مقدار  برای ویژگی ",
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False,
                        help_text="مشخصه اصلی برای محصول است",
                        verbose_name="مشخصه اصلی",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spec_values",
                        to="store.product",
                        verbose_name="محصول",
                    ),
                ),
                (
                    "specification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="store.specification",
                        verbose_name="مشخصه",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقدار مشخصه محصول",
                "verbose_name_plural": "مقادیر مشخصات محصول",
                "unique_together": {("product", "specification")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="specifications",
            field=models.ManyToManyField(
                through="store.ProductSpecification",
                to="store.specification",
                verbose_name="مشخصات",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(related_name="products", to="store.tag"),
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("content", models.TextField(verbose_name="محتوا")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="articles/",
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="منتشر شده"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="store.articlecategory",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="store.tag", verbose_name="تگ\u200cها"
                    ),
                ),
            ],
            options={
                "verbose_name": "مقاله",
                "verbose_name_plural": "مقالات",
            },
        ),
    ]
