# Generated by Django 5.2.1 on 2025-05-17 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='installment_plans',
        ),
        migrations.DeleteModel(
            name='InstallmentPlan',
        ),
    ]
