# Generated by Django 5.2.1 on 2025-06-11 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="category",
        ),
        migrations.RemoveField(
            model_name="article",
            name="tags",
        ),
        migrations.AddField(
            model_name="productspecification",
            name="is_main",
            field=models.BooleanField(
                default=False,
                help_text="مشخصه اصلی برای محصول است",
                verbose_name="مشخصه اصلی",
            ),
        ),
        migrations.AlterField(
            model_name="productoption",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, verbose_name=django.core.validators.MinValueValidator(0)
            ),
        ),
        migrations.DeleteModel(
            name="ArticleCategory",
        ),
        migrations.DeleteModel(
            name="Article",
        ),
    ]
