# Generated by Django 5.2.1 on 2025-05-22 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='discount',
            field=models.PositiveIntegerField(blank=True, help_text='درصد تخفیف', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.RemoveField(
            model_name='product',
            name='discounts',
        ),
        migrations.RenameField(
            model_name='productoption',
            old_name='is_available',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='base_price_cash',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productoption',
            name='discount_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productoption',
            name='discount_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productoption',
            name='is_active_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
