# Generated by Django 5.2.1 on 2025-07-12 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام گروه مشخصات')),
            ],
            options={
                'verbose_name': 'گروه مشخصات',
                'verbose_name_plural': 'گروه\u200cهای مشخصات',
            },
        ),
        migrations.AlterField(
            model_name='specification',
            name='categories',
            field=models.ManyToManyField(related_name='spec_definitions', to='store.category', verbose_name='دسته\u200cبندی\u200cها'),
        ),
        migrations.AddField(
            model_name='specification',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specifications', to='store.specificationgroup', verbose_name='گروه مشخصات'),
        ),
    ]
