# Generated by Django 5.2.1 on 2025-06-11 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="category",
        ),
        migrations.RemoveField(
            model_name="article",
            name="tags",
        ),
        migrations.AddField(
            model_name="productoption",
            name="provider",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="product_option",
                to="accounts.provider",
                verbose_name="تامین کننده ",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ArticleCategory",
        ),
        migrations.DeleteModel(
            name="Article",
        ),
    ]
