# Generated by Django 5.2.1 on 2025-07-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_article_options_alter_articlecategory_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="brand",
        ),
        migrations.AddField(
            model_name="category",
            name="brand",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="categories", to="store.brand"
            ),
        ),
    ]
