# Generated by Django 5.2.1 on 2025-05-22 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_productoption_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='feature_value',
        ),
        migrations.AddField(
            model_name='feature',
            name='value',
            field=models.CharField(default=1, max_length=255, verbose_name='مقدار ویژگی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='feature',
            field=models.ManyToManyField(to='store.feature', verbose_name='ویژگی ها'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام ویژگی'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='store.product'),
        ),
        migrations.RemoveField(
            model_name='feature',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='type',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='updated_at',
        ),
    ]
