# Generated by Django 5.2.1 on 2025-07-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_product_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="title_farsi",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="عنوان فارسی"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=255, verbose_name="عنوان "),
        ),
    ]
