# Generated by Django 5.2.1 on 2025-07-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_specificationgroup_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="brand",
            field=models.ManyToManyField(
                blank=True, related_name="categories", to="store.brand"
            ),
        ),
    ]
