# Generated by Django 5.2.1 on 2025-05-11 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_parent_productoption_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentplan',
            name='monthly_price',
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='prepayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='months',
            field=models.PositiveIntegerField(choices=[(12, 'سالانه'), (18, 'یک و نیم ساله'), (24, 'دو ساله'), (36, 'سه ساله')]),
        ),
    ]
