# Generated by Django 5.2.1 on 2025-07-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_category_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="categories/icons/"
            ),
        ),
    ]
