# Generated by Django 5.2.1 on 2025-07-10 09:56

import colorfield.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_articlecategory_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name': 'دسته\u200cبندی مقاله', 'verbose_name_plural': 'دسته\u200cبندی\u200cهای مقاله'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'برند', 'verbose_name_plural': 'برندها'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'رنگ', 'verbose_name_plural': 'رنگ\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'گالری تصویر', 'verbose_name_plural': 'گالری تصاویر'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productoption',
            options={'verbose_name': 'ویژگی محصول', 'verbose_name_plural': 'ویژگی\u200cهای محصول'},
        ),
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='مثال: #FFFFFF', image_field=None, max_length=7, samples=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#FF0000', 'red'), ('#008000', 'green'), ('#0000FF', 'blue')], verbose_name='کد هگز رنگ'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='product_gallery/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='store.productoption', verbose_name='ویژگی محصول'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='store.color', verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='discount',
            field=models.PositiveIntegerField(blank=True, help_text='درصد تخفیف', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='discount_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان تخفیف'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='discount_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع تخفیف'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='is_active_discount',
            field=models.BooleanField(default=False, verbose_name='تخفیف فعال است؟'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='option_price',
            field=models.PositiveIntegerField(help_text='قیمت به تومان برای محصول با این ویژگی', verbose_name='قیمت ویژگی'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='store.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='registration_required',
            field=models.BooleanField(default=False, verbose_name='نیاز به ثبت گارانتی'),
        ),
    ]
