# Generated by Django 5.2.1 on 2025-05-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productoption',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
