# Generated by Django 5.2.1 on 2025-07-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_category_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productspecification",
            name="bool_value",
        ),
        migrations.RemoveField(
            model_name="productspecification",
            name="decimal_value",
        ),
        migrations.RemoveField(
            model_name="productspecification",
            name="int_value",
        ),
        migrations.RemoveField(
            model_name="productspecification",
            name="str_value",
        ),
        migrations.AddField(
            model_name="productspecification",
            name="specification_value",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="مقدار  برای ویژگی "
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="data_type",
            field=models.CharField(max_length=50, verbose_name="نوع داده"),
        ),
    ]
