# Generated by Django 5.2.1 on 2025-07-23 20:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_article_content_alter_brand_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=ckeditor.fields.RichTextField(verbose_name="محتوا"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="warranty",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="warranty",
            name="terms_conditions",
            field=ckeditor.fields.RichTextField(
                blank=True, verbose_name="شرایط و ضوابط"
            ),
        ),
    ]
