# Generated by Django 5.2.1 on 2025-07-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_remove_productspecification_bool_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productspecification",
            name="specification_value",
            field=models.CharField(
                blank=True, null=True, verbose_name="مقدار  برای ویژگی "
            ),
        ),
    ]
