# Generated by Django 5.2.1 on 2025-05-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_specification_productspecification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='feature',
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.ManyToManyField(through='store.ProductSpecification', to='store.specification', verbose_name='مشخصات'),
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
