# Generated by Django 5.2.1 on 2025-07-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_productspecification_specification_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productspecification",
            name="specification_value",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="مقدار  برای ویژگی "
            ),
        ),
    ]
