# Generated by Django 5.2.1 on 2025-07-16 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_productspecification_specification_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specification",
            name="slug",
        ),
    ]
