# Generated by Django 5.2.1 on 2025-05-25 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_tag_specification_is_main_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام گارانتی')),
                ('company', models.CharField(max_length=100, verbose_name='شرکت ارائه دهنده')),
                ('duration', models.PositiveIntegerField(help_text='مدت زمان گارانتی به ماه', verbose_name='مدت گارانتی (ماه)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('terms_conditions', models.TextField(blank=True, verbose_name='شرایط و ضوابط')),
                ('support_phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس پشتیبانی')),
                ('registration_required', models.BooleanField(default=False, help_text='آیا نیاز به ثبت گارانتی پس از خرید است؟', verbose_name='نیاز به ثبت گارانتی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'گارانتی',
                'verbose_name_plural': 'گارانتی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='productoption',
            name='warranty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_options', to='store.warranty', verbose_name='گارانتی'),
        ),
    ]
