# Generated by Django 5.2 on 2025-05-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_articlecategory_alter_warranty_company_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='store.tag', verbose_name='تگ\u200cها'),
        ),
    ]
