# Generated by Django 5.2.1 on 2025-07-16 22:14

from django.db import migrations, connection

def remove_slug_column(apps, schema_editor):
    """Remove the slug column from store_specification table if it exists"""
    with connection.cursor() as cursor:
        # Check if the column exists and remove it
        cursor.execute("""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'store_specification' 
                    AND column_name = 'slug'
                ) THEN
                    ALTER TABLE store_specification DROP COLUMN slug;
                END IF;
            END $$;
        """)

def reverse_remove_slug_column(apps, schema_editor):
    """Reverse operation - add the slug column back"""
    with connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE store_specification 
            ADD COLUMN slug VARCHAR(255) NULL;
        """)

class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_force_remove_specification_slug"),
    ]

    operations = [
        migrations.RunPython(remove_slug_column, reverse_remove_slug_column),
    ]
