# Generated by Django 5.2.1 on 2025-05-11 17:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان شرایط')),
                ('condition_type', models.CharField(choices=[('automobile', 'خودرو'), ('general', 'عمومی')], default='general', max_length=50, verbose_name='نوع شرایط')),
                ('guarantee_type', models.CharField(choices=[('promissory', 'سفته'), ('check', 'چک'), ('default', 'پیش\u200cفرض (چک)')], default='default', max_length=20, verbose_name='نوع ضمانت')),
                ('has_guarantor', models.BooleanField(default=False, verbose_name='نیاز به ضامن دارد؟')),
                ('condition_months', models.IntegerField(verbose_name='مدت اقساط (ماه)')),
                ('annual_interest_rate_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نرخ سود سالانه (%)')),
                ('initial_increase_percent', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='درصد افزایش اولیه قیمت (%)')),
                ('single_prepayment_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درصد پیش\u200cپرداخت تکی (از قیمت پس از افزایش اولیه)')),
                ('secondary_increase_percent', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='درصد افزایش ثانویه (پس از پیش\u200cپرداخت) (%)')),
                ('delivery_days', models.IntegerField(default=0, verbose_name='زمان تحویل (روز)')),
            ],
            options={
                'verbose_name': 'شرایط وام',
                'verbose_name_plural': 'شرایط وام\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت پایه')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='PrePaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_of_initial_increased_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درصد از قیمت پس از افزایش اولیه')),
                ('days_offset_for_payment', models.IntegerField(verbose_name='فاصله زمانی تا پرداخت (روز)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب پیش\u200cپرداخت')),
                ('loan_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepayment_installments', to='loan_calculator.loancondition', verbose_name='شرایط وام مرتبط')),
            ],
            options={
                'verbose_name': 'قسط پیش\u200cپرداخت',
                'verbose_name_plural': 'اقساط پیش\u200cپرداخت',
                'ordering': ['loan_condition', 'order'],
            },
        ),
        migrations.AddField(
            model_name='loancondition',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_conditions', to='loan_calculator.product', verbose_name='محصول مرتبط'),
        ),
    ]
