# Generated by Django 5.2.1 on 2025-05-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancondition',
            name='condition_type',
            field=models.CharField(choices=[('automobile', 'خودرو'), ('digital', 'دیجیتال'), ('general', 'عمومی')], default='general', max_length=50, verbose_name='نوع شرایط'),
        ),
    ]
