# Generated by Django 5.2.1 on 2025-05-14 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_calculator', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancondition',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_conditions', to='store.product', verbose_name='محصول مرتبط'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
