# Generated by Django 5.2.1 on 2025-06-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('check', 'چک'), ('promissory', 'برات')], default='check', help_text='نوع روش پرداخت قسط', max_length=20)),
                ('period', models.PositiveIntegerField(default=12, help_text='مدت اقساط (ماه)')),
                ('increase_percent', models.FloatField(default=25.0, help_text='نرخ افزایش (درصد)')),
                ('check_period', models.PositiveIntegerField(blank=True, default=13, help_text='دوره ضمانت چک (ماه) فقط برای روش چک', null=True)),
            ],
        ),
    ]
