# Generated by Django 5.2.1 on 2025-07-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInstallmentParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repayment_period', models.PositiveIntegerField(default=12, help_text='مدت بازپرداخت (ماه)', verbose_name='مدت بازپرداخت')),
                ('monthly_interest_percent', models.DecimalField(decimal_places=2, default=1.0, help_text='سود ماهیانه (درصد)', max_digits=5, verbose_name='سود ماهیانه')),
                ('minimum_down_payment', models.DecimalField(decimal_places=2, default=0.0, help_text='حداقل مبلغ پیش\u200cپرداخت', max_digits=10, verbose_name='حداقل پیش\u200cپرداخت')),
                ('guarantee_method', models.CharField(default='check', help_text='نوع ضمانت (مثلا چک، سفته و غیره)', max_length=20, verbose_name='نوع ضمانت')),
                ('applicable_categories', models.ManyToManyField(blank=True, help_text='دسته\u200cبندی\u200cهایی که این روش قسطی شرکتی روی آن\u200cها اعمال می\u200cشود. اگر خالی باشد برای همه محصولات اعمال خواهد شد.', related_name='company_installment_params', to='store.category', verbose_name='دسته\u200cبندی\u200cهای قابل اعمال')),
            ],
            options={
                'verbose_name': 'پارامتر قسط شرکتی',
                'verbose_name_plural': 'پارامترهای قسط شرکتی',
                'ordering': ['repayment_period'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('check', 'چک'), ('promissory', 'سفته')], default='check', help_text='نوع ضمانت (چک یا سفته)', max_length=20, verbose_name='نوع ضمانت')),
                ('repayment_period', models.PositiveIntegerField(default=12, help_text='مدت بازپرداخت (بر حسب ماه)', verbose_name='مدت بازپرداخت')),
                ('initial_increase_percent', models.DecimalField(decimal_places=2, default=25.0, help_text='درصد افزایش اولیه (قبل از محاسبه پیش\u200cپرداخت)', max_digits=5, verbose_name='درصد افزایش اولیه')),
                ('check_guarantee_period', models.PositiveIntegerField(blank=True, default=13, help_text='مدت زمان ضمانت چک (ماه)', null=True, verbose_name='مدت ضمانت چک')),
                ('minimum_down_payment', models.DecimalField(decimal_places=2, default=0.0, help_text='حداقل مبلغ پیش\u200cپرداخت', max_digits=10, verbose_name='حداقل پیش\u200cپرداخت')),
                ('post_down_payment_increase_percent', models.DecimalField(decimal_places=2, default=10.0, help_text='درصد افزایش قیمت پس از کسر پیش\u200cپرداخت', max_digits=5, verbose_name='درصد افزایش پس از پیش\u200cپرداخت')),
                ('bank_tax_interest_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='سود/مالیات بانکی (درصدی)', max_digits=5, verbose_name='سود/مالیات بانکی')),
                ('applicable_categories', models.ManyToManyField(blank=True, help_text='دسته\u200cبندی\u200cهایی که این روش قسطی بانکی روی آن\u200cها اعمال می\u200cشود. اگر خالی باشد برای همه محصولات اعمال خواهد شد.', related_name='bank_installment_params', to='store.category', verbose_name='دسته\u200cبندی\u200cهای قابل اعمال')),
            ],
            options={
                'verbose_name': 'پارامتر قسط بانکی',
                'verbose_name_plural': 'پارامترهای قسط بانکی',
                'ordering': ['method', 'repayment_period'],
            },
        ),
    ]
