# Generated by Django 5.2.1 on 2025-07-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyInstallmentParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "repayment_period",
                    models.PositiveIntegerField(
                        default=12, help_text="مدت بازپرداخت (ماه)"
                    ),
                ),
                (
                    "monthly_interest_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="سود ماهیانه (درصد)",
                        max_digits=5,
                    ),
                ),
                (
                    "minimum_down_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="حداقل مبلغ پیش\u200cپرداخت",
                        max_digits=10,
                    ),
                ),
                (
                    "guarantee_method",
                    models.CharField(
                        default="check",
                        help_text="نوع ضمانت (مثلا چک، سفته و غیره)",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstallmentParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("check", "چک"), ("promissory", "سفته")],
                        default="check",
                        help_text="نوع ضمانت (چک یا سفته)",
                        max_length=20,
                    ),
                ),
                (
                    "repayment_period",
                    models.PositiveIntegerField(
                        default=12, help_text="مدت بازپرداخت (بر حسب ماه)"
                    ),
                ),
                (
                    "initial_increase_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=25.0,
                        help_text="درصد افزایش اولیه (قبل از محاسبه پیش\u200cپرداخت)",
                        max_digits=5,
                    ),
                ),
                (
                    "check_guarantee_period",
                    models.PositiveIntegerField(
                        blank=True,
                        default=13,
                        help_text="مدت زمان ضمانت چک (ماه)",
                        null=True,
                    ),
                ),
                (
                    "minimum_down_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="حداقل مبلغ پیش\u200cپرداخت",
                        max_digits=10,
                    ),
                ),
                (
                    "post_down_payment_increase_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="درصد افزایش قیمت پس از کسر پیش\u200cپرداخت",
                        max_digits=5,
                    ),
                ),
                (
                    "bank_tax_interest_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="سود/مالیات بانکی (درصدی)",
                        max_digits=5,
                    ),
                ),
            ],
        ),
    ]
