# Generated by Django 5.2.1 on 2025-06-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentparameter',
            name='check_period',
        ),
        migrations.RemoveField(
            model_name='installmentparameter',
            name='increase_percent',
        ),
        migrations.RemoveField(
            model_name='installmentparameter',
            name='period',
        ),
        migrations.AddField(
            model_name='installmentparameter',
            name='bank_tax_interest_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='سود/مالیات بانکی (درصدی)', max_digits=5),
        ),
        migrations.AddField(
            model_name='installmentparameter',
            name='check_guarantee_period',
            field=models.PositiveIntegerField(blank=True, default=13, help_text='مدت زمان ضمانت چک (ماه)', null=True),
        ),
        migrations.AddField(
            model_name='installmentparameter',
            name='initial_increase_percent',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='درصد افزایش اولیه (قبل از محاسبه پیش\u200cپرداخت)', max_digits=5),
        ),
        migrations.AddField(
            model_name='installmentparameter',
            name='minimum_down_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='حداقل مبلغ پیش\u200cپرداخت', max_digits=10),
        ),
        migrations.AddField(
            model_name='installmentparameter',
            name='post_down_payment_increase_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='درصد افزایش قیمت پس از کسر پیش\u200cپرداخت', max_digits=5),
        ),
        migrations.AddField(
            model_name='installmentparameter',
            name='repayment_period',
            field=models.PositiveIntegerField(default=12, help_text='مدت بازپرداخت (بر حسب ماه)'),
        ),
        migrations.AlterField(
            model_name='installmentparameter',
            name='method',
            field=models.CharField(choices=[('check', 'چک'), ('promissory', 'سفته')], default='check', help_text='نوع ضمانت (چک یا سفته)', max_length=20),
        ),
    ]
