# Generated by Django 5.2.1 on 2025-06-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0002_remove_installmentparameter_check_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentparameter',
            name='param_type',
            field=models.CharField(choices=[('company', 'شرایط شرکت'), ('bank', 'شرایط بانکی')], default='company', max_length=10, verbose_name='نوع تنظیمات'),
        ),
    ]
