# Generated by Django 5.2.1 on 2025-06-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0002_remove_installmentparameter_check_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInstallmentParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repayment_period', models.PositiveIntegerField(default=12, help_text='مدت بازپرداخت (ماه)')),
                ('monthly_interest_percent', models.DecimalField(decimal_places=2, default=1.0, help_text='سود ماهیانه (درصد)', max_digits=5)),
                ('minimum_down_payment', models.DecimalField(decimal_places=2, default=0.0, help_text='حداقل مبلغ پیش\u200cپرداخت', max_digits=10)),
                ('guarantee_method', models.CharField(default='check', help_text='نوع ضمانت (مثلا چک، سفته و غیره)', max_length=20)),
            ],
        ),
    ]
