# Generated by Django 5.2.1 on 2025-07-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0003_companyinstallmentparameter'),
        ('store', '0003_articlecategory_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinstallmentparameter',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, help_text='دسته\u200cبندی\u200cهایی که این روش قسطی شرکتی روی آن\u200cها اعمال می\u200cشود. اگر خالی باشد برای همه محصولات اعمال خواهد شد.', related_name='company_installment_params', to='store.category'),
        ),
        migrations.AddField(
            model_name='installmentparameter',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, help_text='دسته\u200cبندی\u200cهایی که این روش قسطی بانکی روی آن\u200cها اعمال می\u200cشود. اگر خالی باشد برای همه محصولات اعمال خواهد شد.', related_name='bank_installment_params', to='store.category'),
        ),
    ]
