# Generated by Django 5.2.1 on 2025-06-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0003_companyinstallmentparameter'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinstallmentparameter',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='اگر خالی باشد، برای همه محصولات فعال است.', related_name='company_installments', to='store.product', verbose_name='محصولات مجاز'),
        ),
        migrations.AddField(
            model_name='installmentparameter',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='اگر خالی باشد، برای همه محصولات فعال است.', related_name='bank_installments', to='store.product', verbose_name='محصولات مجاز'),
        ),
    ]
