# Generated by Django 5.2.1 on 2025-07-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0004_companyinstallmentparameter_applicable_categories_and_more'),
        ('store', '0005_alter_tag_options_alter_tag_name_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinstallmentparameter',
            options={'ordering': ['repayment_period'], 'verbose_name': 'پارامتر قسط شرکتی', 'verbose_name_plural': 'پارامترهای قسط شرکتی'},
        ),
        migrations.AlterModelOptions(
            name='installmentparameter',
            options={'ordering': ['method', 'repayment_period'], 'verbose_name': 'پارامتر قسط بانکی', 'verbose_name_plural': 'پارامترهای قسط بانکی'},
        ),
        migrations.AlterField(
            model_name='companyinstallmentparameter',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, help_text='دسته\u200cبندی\u200cهایی که این روش قسطی شرکتی روی آن\u200cها اعمال می\u200cشود. اگر خالی باشد برای همه محصولات اعمال خواهد شد.', related_name='company_installment_params', to='store.category', verbose_name='دسته\u200cبندی\u200cهای قابل اعمال'),
        ),
        migrations.AlterField(
            model_name='companyinstallmentparameter',
            name='guarantee_method',
            field=models.CharField(default='check', help_text='نوع ضمانت (مثلا چک، سفته و غیره)', max_length=20, verbose_name='نوع ضمانت'),
        ),
        migrations.AlterField(
            model_name='companyinstallmentparameter',
            name='minimum_down_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='حداقل مبلغ پیش\u200cپرداخت', max_digits=10, verbose_name='حداقل پیش\u200cپرداخت'),
        ),
        migrations.AlterField(
            model_name='companyinstallmentparameter',
            name='monthly_interest_percent',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='سود ماهیانه (درصد)', max_digits=5, verbose_name='سود ماهیانه'),
        ),
        migrations.AlterField(
            model_name='companyinstallmentparameter',
            name='repayment_period',
            field=models.PositiveIntegerField(default=12, help_text='مدت بازپرداخت (ماه)', verbose_name='مدت بازپرداخت'),
        ),
        migrations.AlterField(
            model_name='installmentparameter',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, help_text='دسته\u200cبندی\u200cهایی که این روش قسطی بانکی روی آن\u200cها اعمال می\u200cشود. اگر خالی باشد برای همه محصولات اعمال خواهد شد.', related_name='bank_installment_params', to='store.category', verbose_name='دسته\u200cبندی\u200cهای قابل اعمال'),
        ),
        migrations.AlterField(
            model_name='installmentparameter',
            name='bank_tax_interest_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='سود/مالیات بانکی (درصدی)', max_digits=5, verbose_name='سود/مالیات بانکی'),
        ),
        migrations.AlterField(
            model_name='installmentparameter',
            name='check_guarantee_period',
            field=models.PositiveIntegerField(blank=True, default=13, help_text='مدت زمان ضمانت چک (ماه)', null=True, verbose_name='مدت ضمانت چک'),
        ),
        migrations.AlterField(
            model_name='installmentparameter',
            name='initial_increase_percent',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='درصد افزایش اولیه (قبل از محاسبه پیش\u200cپرداخت)', max_digits=5, verbose_name='درصد افزایش اولیه'),
        ),
        migrations.AlterField(
            model_name='installmentparameter',
            name='method',
            field=models.CharField(choices=[('check', 'چک'), ('promissory', 'سفته')], default='check', help_text='نوع ضمانت (چک یا سفته)', max_length=20, verbose_name='نوع ضمانت'),
        ),
        migrations.AlterField(
            model_name='installmentparameter',
            name='minimum_down_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='حداقل مبلغ پیش\u200cپرداخت', max_digits=10, verbose_name='حداقل پیش\u200cپرداخت'),
        ),
        migrations.AlterField(
            model_name='installmentparameter',
            name='post_down_payment_increase_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='درصد افزایش قیمت پس از کسر پیش\u200cپرداخت', max_digits=5, verbose_name='درصد افزایش پس از پیش\u200cپرداخت'),
        ),
        migrations.AlterField(
            model_name='installmentparameter',
            name='repayment_period',
            field=models.PositiveIntegerField(default=12, help_text='مدت بازپرداخت (بر حسب ماه)', verbose_name='مدت بازپرداخت'),
        ),
    ]
