# Generated by Django 5.2.1 on 2025-07-09 10:52

import accounts.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="شماره تلفن باید با +98 یا 09 شروع شده و 11 رقم باشد (مثلاً: +989123456789 یا 09123456789).",
                                regex="^(?:\\+98|0)?9\\d{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "is_phone_verified",
                    models.BooleanField(default=False, verbose_name="تأیید شماره تلفن"),
                ),
                (
                    "verification_code",
                    models.CharField(
                        blank=True, max_length=6, null=True, verbose_name="کد تأیید"
                    ),
                ),
                (
                    "verification_code_created_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان ایجاد کد تأیید"
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="کد ملی باید دقیقاً 10 رقم باشد",
                                regex="^\\d{10}$",
                            ),
                            accounts.models.validate_national_id,
                        ],
                        verbose_name="کد ملی",
                    ),
                ),
                (
                    "economic_code",
                    models.CharField(
                        blank=True, max_length=12, null=True, verbose_name="کد اقتصادی"
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_address", models.CharField(max_length=50)),
                ("province", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("full_address", models.TextField()),
                (
                    "postcode",
                    models.CharField(
                        max_length=10,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name=" مشتری",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "موبایل"),
                            ("tablet", "تبلت"),
                            ("desktop", "دسکتاپ"),
                            ("web", "وب"),
                            ("other", "سایر"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("token_hash", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_used", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "توکن دستگاه",
                "verbose_name_plural": "توکن\u200cهای دستگاه",
                "ordering": ["-last_used"],
            },
        ),
        migrations.CreateModel(
            name="FavProductList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name=" مشتری",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                ("message", models.TextField(verbose_name="متن پیام")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("info", "اطلاعات"),
                            ("success", "موفقیت"),
                            ("warning", "هشدار"),
                            ("danger", "خطر"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="نوع اعلان",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="خوانده شده"),
                ),
                (
                    "related_url",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="لینک مرتبط"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "اعلان",
                "verbose_name_plural": "اعلان\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OfferCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=50, verbose_name="کد تخفیف")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used", models.BooleanField(default=False)),
                (
                    "users",
                    models.ManyToManyField(
                        to=settings.AUTH_USER_MODEL, verbose_name="کاربر "
                    ),
                ),
            ],
            options={
                "verbose_name": "کد تخفیف",
                "verbose_name_plural": "کدهای تخفیف",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legal_info",
                    models.TextField(
                        blank=True, null=True, verbose_name="اطلاعات حقوقی"
                    ),
                ),
                (
                    "refund_method",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="روش بازگرداندن پول",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="نام شرکت"
                    ),
                ),
                (
                    "company_registration_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="شماره ثبت شرکت",
                    ),
                ),
                (
                    "company_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="توضیحات شرکت"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تامین کننده ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ارائه دهنده",
                "verbose_name_plural": "ارائه دهندگان",
            },
        ),
    ]
