# Generated by Django 5.2.1 on 2025-06-25 23:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "موبایل"),
                            ("tablet", "تبلت"),
                            ("desktop", "دسکتاپ"),
                            ("web", "وب"),
                            ("other", "سایر"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("token_hash", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_used", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "توکن دستگاه",
                "verbose_name_plural": "توکن\u200cهای دستگاه",
                "ordering": ["-last_used"],
            },
        ),
    ]
