# Generated by Django 5.2.1 on 2025-07-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="favproductlist",
            name="products",
            field=models.ManyToManyField(
                to="store.product", verbose_name="محصولات مورد علاقه"
            ),
        ),
    ]
