# Generated by Django 5.2.1 on 2025-06-27 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_devicetoken"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="client",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="favproductlist",
            old_name="client",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="client",
            new_name="user",
        ),
    ]
