# Generated by Django 5.2.1 on 2025-05-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_economic_code_and_more'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fav_Product_List',
            new_name='FavProductList',
        ),
        migrations.RenameModel(
            old_name='Offer_Code',
            new_name='OfferCode',
        ),
    ]
