# Generated by Django 5.2.1 on 2025-05-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_fav_product_list_favproductlist_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offercode',
            options={'verbose_name': 'کد تخفیف', 'verbose_name_plural': 'کدهای تخفیف'},
        ),
        migrations.AddField(
            model_name='offercode',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
