# Generated by Django 5.2.1 on 2025-07-11 21:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExcelFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان فایل")),
                (
                    "file",
                    models.FileField(
                        upload_to="excel_files/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["xlsx", "xls"]
                            )
                        ],
                        verbose_name="فایل Excel",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("products", "محصولات"),
                            ("categories", "دسته\u200cبندی\u200cها"),
                            ("brands", "برندها"),
                            ("specifications", "مشخصات"),
                            ("colors", "رنگ\u200cها"),
                            ("warranties", "گارانتی\u200cها"),
                        ],
                        max_length=20,
                        verbose_name="نوع فایل",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار پردازش"),
                            ("processing", "در حال پردازش"),
                            ("completed", "تکمیل شده"),
                            ("failed", "ناموفق"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ آپلود"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ پردازش"
                    ),
                ),
                (
                    "total_rows",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد کل ردیف\u200cها"
                    ),
                ),
                (
                    "processed_rows",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد ردیف\u200cهای پردازش شده"
                    ),
                ),
                (
                    "error_rows",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد ردیف\u200cهای دارای خطا"
                    ),
                ),
            ],
            options={
                "verbose_name": "فایل Excel",
                "verbose_name_plural": "فایل\u200cهای Excel",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ExcelImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="شماره ردیف"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "اطلاعات"),
                            ("warning", "هشدار"),
                            ("error", "خطا"),
                            ("success", "موفق"),
                        ],
                        max_length=10,
                        verbose_name="سطح",
                    ),
                ),
                ("message", models.TextField(verbose_name="پیام")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "excel_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="excel_file_handling.excelfile",
                        verbose_name="فایل Excel",
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ import",
                "verbose_name_plural": "لاگ\u200cهای import",
                "ordering": ["-created_at"],
            },
        ),
    ]
