# Generated by Django 5.2.1 on 2025-07-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("excel_file_handling", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="excelfile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("products", "محصولات"),
                    ("categories", "دسته\u200cبندی\u200cها"),
                    ("brands", "برندها"),
                    ("specifications", "مشخصات"),
                    ("specification_groups", "گروه\u200cهای مشخصات"),
                    ("colors", "رنگ\u200cها"),
                    ("warranties", "گارانتی\u200cها"),
                    ("tags", "تگ\u200cها"),
                    ("product_options", "ویژگی\u200cهای محصول"),
                    ("product_specifications", "مقادیر مشخصات محصول"),
                    ("articles", "مقالات"),
                    ("article_categories", "دسته\u200cبندی\u200cهای مقاله"),
                ],
                max_length=30,
                verbose_name="نوع فایل",
            ),
        ),
    ]
