# Generated by Django 5.2.1 on 2025-07-09 13:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="guest_id",
            field=models.CharField(
                blank=True,
                default=uuid.uuid4,
                editable=False,
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
